cli: Implement 'shelley transaction build-raw' for Shelley addresses
Not yet able to do this for Byrin addresses, because they need to be
converted to Shelley bootstrap addresses in 'ledger-specs' and that
is not done yet.

diff --git a/cardano-cli/test/cli/core/common b/cardano-cli/test/cli/core/common
--- a/cardano-cli/test/cli/core/common
+++ b/cardano-cli/test/cli/core/common
@@ -75,6 +75,13 @@ assert_file_exists () {
     fi
 }
 
+fail_on_error () {
+  if test "$1" -ne 0 ; then
+    echo "Error code: $1"
+    exit "$1"
+    fi
+}
+
 report_result () {
   if test "${1}" = 0 ; then
     RESULT="${colourGreen}PASSED [ ${testname} ]${colourReset}"
