Ensure build-complete job fails if build jobs fail

diff --git a/.github/workflows/haskell-linux.yml b/.github/workflows/haskell-linux.yml
--- a/.github/workflows/haskell-linux.yml
+++ b/.github/workflows/haskell-linux.yml
@@ -19,7 +19,7 @@ on:
         default: some
 
 jobs:
-  linux_ci:
+  build:
     runs-on: ${{ matrix.os }}
 
     strategy:
@@ -231,14 +231,21 @@ jobs:
     #     limit-access-to-actor: true
 
   build-complete:
-    needs: [linux_ci]
+    needs: [build]
     runs-on: ubuntu-latest
+    if: ${{ always() }}
     steps:
-    - name: Build complete
-      run: echo 'Build complete'
+    - name: Builds jobs complete
+      run: |
+        if ${{ needs.build.result }}; then
+          echo 'Linux CI job passed'
+        else
+          echo 'Linux CI job failed'
+          exit 1
+        fi
 
   release:
-    needs: [linux_ci]
+    needs: [build]
     if: ${{ startsWith(github.ref, 'refs/tags') }}
     runs-on: ubuntu-latest
     steps:
diff --git a/.github/workflows/haskell.yml b/.github/workflows/haskell.yml
--- a/.github/workflows/haskell.yml
+++ b/.github/workflows/haskell.yml
@@ -262,9 +262,16 @@ jobs:
   build-complete:
     needs: [build]
     runs-on: ubuntu-latest
+    if: ${{ always() }}
     steps:
-    - name: Build complete
-      run: echo 'Build complete'
+    - name: Builds jobs complete
+      run: |
+        if ${{ needs.linux_ci.result }}; then
+          echo 'Linux CI job passed'
+        else
+          echo 'Linux CI job failed'
+          exit 1
+        fi
 
   release:
     needs: [build]
